<?php include 'header.phtml'?>

<form action="añadirCategorias" method ="POST" class="my-4" enctype= "multipart/form-data">

        <div class="row">
            <h3>Agregar Categorias</h3>
        
                <div class="col3">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Categoria</label>
                            <input name="nombre"type="text" class="form-control">
                        </div>
                    </div>
                </div>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
</form>