<?php include 'header.phtml'?>


<form action="editarDestinos/<?php echo $destinos[0]->id_destinos ?>" method ="POST" class="my-4">
    <div class="row">
        <h3>Editar Destinos</h3>
            <div class="col3">
                <div class="form-group">
                    <label>Pais</label>
                    <input name="pais" value = "<?php echo $destinos[0]->pais ?>"type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label>Ciudad</label>
                    <input name="ciudad" value = "<?php echo $destinos[0]->ciudad ?>"type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label>Actividades</label>
                    <input name="actividades" value = "<?php echo $destinos[0]->actividades ?>"type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label>PRECIO</label>
                    <input name="precio" value = "<?php echo $destinos[0]->precio ?>" type="number" class="form-control">
                </div>
            </div>
        </div>
<button type="submit" class="btn btn-primary">Guardar</button>

</form>