<?php 
include 'header.phtml';
?>
<h2>Destinos:</h2>
<ul class='destinos-db'>
<?php   foreach($destinos as $destino){ 
?>
                <h4 class ='listado_destinos'><?php echo 'Pertenece a la categoria' ?></b>(<?php echo $destino->categoria_nombre ?>)</h4>
                        
                <div class ='listado_destinos'> 
                        <li class = "lista_items"><b><?php echo 'Pais' ?></b> | (<?php echo $destino -> pais ?>) </b> </li>  
                        <li class = "lista_items"><b><?php echo 'Ciudad' ?></b> | (<?php echo $destino -> ciudad ?>) </b> </li>
                        <li class = "lista_items"><b><?php echo 'Actividad' ?></b> | (<?php echo $destino -> actividades ?>) </b> </li>
                        <li class = "lista_items"><b><?php echo 'Precio' ?></b> | (<?php echo $destino -> precio ?>) </b> </li>   
                        <a href= "borrarDestinos/<?php echo $destino->id_destinos ?>" type = "button" class = 'btn btn-danger ml-auto borrar-destinos'>Borrar</a> 
                        <a href= "editarDestinos/<?php echo $destino->id_destinos ?>" type = "button" class = 'btn btn-danger ml-auto editar-destinos'>Editar</a>           
                        <a href= "mostrar/<?php echo $destino->id_destinos ?>" class = 'btn btn-primary'>visualizar</a>
                </div>
<?php 
        }
?>
</ul>

